spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/chromispos
    username: chromispos
    password: toor
#    url: jdbc:postgresql://192.168.1.40:5432/chromispos
#    username: chromispos
#    password: chromispos
  jpa:
    hibernate:
      ddl-auto: none
  show-sql: true
  
server:
  port: 8082

logging:
  level:
    org:
      hibernate:
        SQL: debug
      springframework:
        web: debug
#  pattern:
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#  file: logs/chromis.log
#  config: classpath:config/logback.xml
  
  
  
---
spring:
  profiles: prod
  datasource:
#    url: jdbc:postgresql://localhost:5432/chromispos
#    username: chromispos
#    password: chromispos
    url: jdbc:postgresql://192.168.1.40:5432/chromispos
    username: chromispos
    password: chromispos
#    url: jdbc:postgresql://192.168.1.113:5432/chromispos
#    username: chromispos
#    password: chromispos
  jpa:
    hibernate:
      ddl-auto: none
  show-sql: true
  
server:
  port: 8082
  
logging:
  level:
    org:
      hibernate:
        SQL: debug
      springframework:
        web: debug
      
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: logs/chromis.log
  config: classpath:config/logback.xml